// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQrVzHAnlWVdWbF1nsRYc18nNGaQ9j5vo',
    appId: '1:787727007198:web:495ecd3c992fd702ddb14f',
    messagingSenderId: '787727007198',
    projectId: 'authtutorial-da688',
    authDomain: 'authtutorial-da688.firebaseapp.com',
    storageBucket: 'authtutorial-da688.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEbP7GO6kSJLVtcdu8aVnVc-GO8SZF3rk',
    appId: '1:787727007198:android:b50e878d9b2b6d31ddb14f',
    messagingSenderId: '787727007198',
    projectId: 'authtutorial-da688',
    storageBucket: 'authtutorial-da688.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARX3PZGduI-BAd_qEumQP_SV7A1yxcIFQ',
    appId: '1:787727007198:ios:f42963569abb5d0fddb14f',
    messagingSenderId: '787727007198',
    projectId: 'authtutorial-da688',
    storageBucket: 'authtutorial-da688.appspot.com',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARX3PZGduI-BAd_qEumQP_SV7A1yxcIFQ',
    appId: '1:787727007198:ios:f5c3625e1ceeb8f3ddb14f',
    messagingSenderId: '787727007198',
    projectId: 'authtutorial-da688',
    storageBucket: 'authtutorial-da688.appspot.com',
    iosBundleId: 'com.example.todoList.RunnerTests',
  );
}
